{
 "title": "hook dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "plugin",
    "label": "plugin",
    "query": "label_values(prow_plugin_handle_duration_seconds_bucket, plugin)"
   },
   {
    "name": "event_type",
    "label": "event_type",
    "query": "label_values(prow_plugin_handle_duration_seconds_bucket, event_type)"
   },
   {
    "name": "action",
    "label": "action",
    "query": "label_values(prow_plugin_handle_duration_seconds_bucket, action)"
   }
  ]
 },
 "panels": [
  {
   "title": "webhook counter",
   "type": "singlestat",
   "description": "sum(prow_webhook_counter)",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(prow_webhook_counter)" }
   ]
  },
  {
   "title": "webhook response codes",
   "type": "singlestat",
   "description": "sum(prow_webhook_response_codes)",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prow_webhook_response_codes)"
    }
   ]
  },
  {
   "title": "incoming webhooks by event type",
   "type": "graph",
   "description": "sum(rate(prow_webhook_counter[1m])) by (event_type)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prow_webhook_counter[1m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "webhook response codes",
   "type": "graph",
   "description": "sum(rate(prow_webhook_response_codes[1m])) by (response_code)",
   "gridPos": { "h": 9, "w": 24, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prow_webhook_response_codes[1m])) by (response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "configmap capacities",
   "type": "graph",
   "description": "prow_configmap_size_bytes / 1048576",
   "gridPos": { "h": 9, "w": 24, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "prow_configmap_size_bytes / 1048576",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Response latency percentiles for event type ${event_type}, action ${action} by plugin ${plugin}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prow_plugin_handle_duration_seconds_bucket{plugin=~\"${plugin}\", event_type=~\"${event_type}\", action=~\"${action}\"}[5m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(prow_plugin_handle_duration_seconds_bucket{plugin=~\"${plugin}\", event_type=~\"${event_type}\", action=~\"${action}\"}[5m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(prow_plugin_handle_duration_seconds_bucket{plugin=~\"${plugin}\", event_type=~\"${event_type}\", action=~\"${action}\"}[5m])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  }
 ]
}